// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZvpYmTptH4EHiXTJhdU2dlKf809jU1ZU',
    appId: '1:383597021083:web:20bbee0a30e2eca9bc433e',
    messagingSenderId: '383597021083',
    projectId: 'perros-sos-4dd7a',
    authDomain: 'perros-sos-4dd7a.firebaseapp.com',
    storageBucket: 'perros-sos-4dd7a.appspot.com',
    measurementId: 'G-ZZ772XNR39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXL9hqOpxTuFDFywmItcO-53VSL0NeoE',
    appId: '1:383597021083:android:e3385d345e459f7fbc433e',
    messagingSenderId: '383597021083',
    projectId: 'perros-sos-4dd7a',
    storageBucket: 'perros-sos-4dd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5fwsJbAKWg7eHzO2NttXIsThiwGTPtIc',
    appId: '1:383597021083:ios:001284f3313110f6bc433e',
    messagingSenderId: '383597021083',
    projectId: 'perros-sos-4dd7a',
    storageBucket: 'perros-sos-4dd7a.appspot.com',
    iosBundleId: 'com.example.perrosSos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5fwsJbAKWg7eHzO2NttXIsThiwGTPtIc',
    appId: '1:383597021083:ios:001284f3313110f6bc433e',
    messagingSenderId: '383597021083',
    projectId: 'perros-sos-4dd7a',
    storageBucket: 'perros-sos-4dd7a.appspot.com',
    iosBundleId: 'com.example.perrosSos',
  );
}
